# Server Configuration
server.port=8080
spring.application.name=file-storage-backend

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/filestorage
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# File Storage Path
file.storage.location=./uploads

# AWS S3 Configuration
aws.s3.bucket-name=flie-storage-blob-test
aws.s3.region=us-east-1
aws.s3.access-key=AKIAVRUVSYHAQME5NBIM
aws.s3.secret-key=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
# Presigned URL expiration time in minutes
aws.s3.presigned-url-expiration=15

# JWT Configuration
# Secure 512-bit key for HS512 (base64-encoded)
jwt.secret=k3pYz9vR2xL8mN5wQ7tU1jH4fG6aS0dF9xC3vB8nM2kP5wR7yT1qU4eI6oL0zX3bN9mK2jH5gS8aD1fC4vB7n
jwt.expiration=86400000

# CORS Configuration
cors.allowed.origins=http://localhost:4200

# Kafka Configuration
spring.kafka.bootstrap-servers=10.80.134.246:9092,10.80.134.246:9093,10.80.134.246:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.retry.backoff.ms=1000

# Kafka Topics
app.kafka.topic.file-upload-completed=file-storage-group
